### ISSUE TITLE
Show rate if rate is used in game

### ISSUE THREAD

**Issue by klariionn** [flashflashrevolution/web-stream-overlay#3]
It can get confusing to viewers if say I'm using 0.9x and the overlay shows just the song without the rate, so adding the rate in would help out on streams on viewer side.

**Comment by Psycast** [comment]
Resolved in https://github.com/flashflashrevolution/web-stream-overlay/commit/e2d8f7b4a1aa22129ce7027cc031bd749f21cf18.
